  name : tests_workflow

  on:
    push:
      branches:
        - developement

  jobs:
    job1 :
      runs-on: ubuntu-latest
      steps:
          - name: Checkout
          - uses: actions/checkout@v3

          - name: compiler
          - run: javac *.java

          - name: lancer les tests
          - uses:
